FROM node:22-alpine

WORKDIR /workspace

COPY package.json package-lock.json ./
COPY api/package.json ./api/
COPY api/prisma ./api/prisma
COPY app/package.json ./app/

RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:api"]
