FROM node:22-alpine

WORKDIR /workspace

COPY package.json package-lock.json ./
COPY docker-entrypoint.dev.sh /usr/local/bin/docker-entrypoint.dev.sh
COPY prisma ./prisma

RUN npm ci \
  && chmod +x /usr/local/bin/docker-entrypoint.dev.sh

COPY . .

EXPOSE 3000

ENTRYPOINT ["docker-entrypoint.dev.sh"]
CMD ["npm", "run", "start:dev"]
